name: Run tests

# Disparadores automáticos e manuais
on: 
  push:
    branches: [master]
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        node-version: [14.x]
      strategy:
        max_attempts: 3  

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
        
    - run: npm install
    
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        spec: cypress/integration/form.feature
